#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_UNKNOWN,
    SP_NAME_BANDANA,
    SP_NAME_WISE,
    SP_NAME_DEDEDE,
    SP_NAME_GOOEY,
    SP_NAME_MAGOLOR,
    SP_NAME_DAROACH,
    SP_NAME_FRANCISCA,
    SP_NAME_FLAMBERGE,
    SP_NAME_ZAN,
    SP_NAME_ADELEINE,
    SP_NAME_RIBBON,
    SP_NAME_MARX,
    SP_NAME_TARANZA,
    SP_NAME_LEON,
    SP_NAME_CAROL,
    SP_NAME_SUSIE,
    SP_NAME_WHISPY,
    SP_NAME_LOLOLO,
    SP_NAME_LALALA,
    SP_NAME_KABULA,
    SP_NAME_KRACKO,
    SP_NAME_NIGHTMARE,
    SP_NAME_PITCH,
    SP_NAME_KINE,
    SP_NAME_NAGO,
    SP_NAME_RICK,
    SP_NAME_CHUCHU,
    SP_NAME_ELFILIN,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
