#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(SUPER_FANG) \
    F(SWIFT) \
    F(WEATHER_BALL) \
    F(FACADE) \
    F(HYPER_VOICE) \
    F(HYPER_BEAM) \
    F(GIGA_IMPACT) \
    F(SWORDS_DANCE) \
    F(PROTECT) \
    F(SUBSTITUTE) \
    F(ROAR) \
    F(FIRE_SPIN) \
    F(FIRE_PUNCH) \
    F(BLAZE_KICK) \
    F(FLAMETHROWER) \
    F(FIRE_BLAST) \
    F(WILL_O_WISP) \
    F(SUNNY_DAY) \
    F(AQUA_JET) \
    F(BRINE) \
    F(TRIPLE_DIVE) \
    F(SURF) \
    F(RAIN_DANCE) \
    F(TRAILBLAZE) \
    F(BULLET_SEED) \
    F(ENERGY_BALL) \
    F(SOLAR_BEAM) \
    F(LEECH_SEED) \
    F(CHARGE_BEAM) \
    F(THUNDER_PUNCH) \
    F(THUNDERBOLT) \
    F(SUPERCELL_SLAM) \
    F(THUNDER) \
    F(THUNDER_WAVE) \
    F(MAGNET_RISE) \
    F(CLEAR_SMOG) \
    F(POISON_JAB) \
    F(SLUDGE_BOMB) \
    F(TOXIC) \
    F(ROCK_SMASH) \
    F(ARM_THRUST) \
    F(LOW_KICK) \
    F(STORM_THROW) \
    F(BODY_PRESS) \
    F(FOCUS_BLAST) \
    F(PSYCHIC_FANGS) \
    F(PSYCHIC) \
    F(REST) \
    F(CALM_MIND) \
    F(REFLECT) \
    F(LIGHT_SCREEN) \
    F(SKILL_SWAP) \
    F(TRICK) \
    F(POUNCE) \
    F(U_TURN) \
    F(X_SCISSOR) \
    F(POLLEN_PUFF) \
    F(HEX) \
    F(SHADOW_CLAW) \
    F(PHANTOM_FORCE) \
    F(SHADOW_BALL) \
    F(CONFUSE_RAY) \
    F(CURSE) \
    F(THIEF) \
    F(SNARL) \
    F(JAW_LOCK) \
    F(DARK_PULSE) \
    F(FLING) \
    F(TAUNT) \
    F(HONE_CLAWS) \
    F(FAKE_TEARS) \
    F(ROCK_SLIDE) \
    F(POWER_GEM) \
    F(STONE_EDGE) \
    F(SANDSTORM) \
    F(SCORCHING_SANDS) \
    F(DIG) \
    F(EARTHQUAKE) \
    F(SPIKES) \
    F(HEAVY_SLAM) \
    F(FLASH_CANNON) \
    F(IRON_TAIL) \
    F(IRON_DEFENSE) \
    F(PLUCK) \
    F(HURRICANE) \
    F(ACROBATICS) \
    F(DEFOG) \
    F(BREAKING_SWIPE) \
    F(DRAGON_PULSE) \
    F(DRAGON_HAMMER) \
    F(ICE_PUNCH) \
    F(ICE_SPINNER) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(MIST) \
    F(SNOWSCAPE) \
    F(DRAINING_KISS) \
    F(DAZZLING_GLEAM) \
    F(PLAY_ROUGH) \
    F(CHARM)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(WAVE_CRASH) \
    F(STRENGTH) \
    F(FLASH) \
    F(SUBMISSION) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
