gText_Birch_Welcome::
	.string "Hello! How do you do?\p"
	.string "They call me Wise Waddle Dee.\p"
	.string "And it is my great honor to welcome you\n"
	.string "to the world of Dream Land!\p"
	.string "Lately, our land has been abuzz with all\n"
	.string "sorts of interesting developments…\p"
	.string "$"

gText_Birch_Pokemon::
	.string "…not the least of which are the”\n"
	.string "mysterious allies we call “Helpers”!”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Species from all across Planet Popstar,\n"
	.string "and even some from beyond, have begun\l"
	.string "appearing in great numbers here.\p"
	.string "They all share one thing in common: a\n"
	.string "strong sense of loyalty.\p"
	.string "Their instinct is to seek camaraderie\n"
	.string "with a trustworthy and capable leader.\p"
	.string "But how many species of Helpers exist?\n"
	.string "What inspires their unusual behavior?\p"
	.string "And just what has caused their sudden\n"
	.string "appearance throughout Dream Land…?\p"
	.string "That's the focus of my research.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, before I forget, there's\n"
	.string "someone else I must introduce…"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Before you set off, I'll need a name for\n"
	.string "your save file!$"

gText_Birch_WhatsYourName::
	.string "Meet Kirby! He'll be the star of this\n"
	.string "show.\p"
	.string "Through his eyes, you'll explore Dream\n"
	.string "Land, form a team of invaluable allies,\l"
	.string "and uncover the story behind Helpers.\p"
	.string "Before you set off, though, I'll need a\n"
	.string "name for your save file!$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN}? Is that correct?$"

gText_Birch_YourePlayer::
	.string "Perfect! Thank you, {PLAYER}{KUN}! I've\n"
	.string "jotted it down for you.\p"
	.string "I won't keep you waiting any longer.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready now?\p"
	.string "A brand new adventure is about\n"
	.string "to unfold.\p"
	.string "Dreams, adventure, and friendship await\n"
	.string "you, Kirby, and all of Dream Land!\p"
	.string "It won't be too long until we meet\n"
	.string "again, I'm sure. But until then…\p"
	.string "Take care now!\p"
	.string "$"
