gText_Birch_Welcome::
	.string "Hello! How do you do?\p"
	.string "They call me Wise Waddle Dee.\p"
	.string "And it is my great honor to welcome\n"
	.string "you to the world of Dream Land!\p"
	.string "Lately, our land has been abuzz\n"
	.string "with interesting developments...\p"
	.string "$"

gText_Birch_Pokemon::
	.string "...not the least of which are”\n"
	.string "what we call 'Helpers'!”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Species from all across Planet\n"
	.string "Popstar, and even some from beyond,\l"
	.string "have been appearing in droves!\p"
	.string "They all share one thing in common:\n"
	.string "a strong sense of loyalty.\p"
	.string "Their instinct is to work under the\n"
	.string "camaraderie of a capable partner.\p"
	.string "But how many helper species exist?\n"
	.string "Why is their behavior so friendly?\p"
	.string "And just what has caused them to\n"
	.string "swarm throughout Dream Land...?\p"
	.string "That's the focus of my research.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, before I forget, there's\n"
	.string "someone else to introduce..."
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Before you set off, I'll just\n"
	.string "need a name for your save file!$"

gText_Birch_WhatsYourName::
	.string "Meet Kirby!\n"
	.string "He'll be the star of this show.\p"
	.string "Through his eyes, you'll explore\n"
	.string "Dream Land, form an invaluable\l"
	.string "team of companions, and learn\l"
	.string "the mysteries of helpers.\p"
	.string "Before you set off, I'll just\n"
	.string "need a name for your save file!$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN}? Is that correct?$"

gText_Birch_YourePlayer::
	.string "Perfect! Thank you, {PLAYER}{KUN}!\p"
	.string "I've jotted it down right here.\n"
	.string "I won't keep you waiting any longer.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready now?\p"
	.string "A brand new adventure is about\n"
	.string "to unfold.\p"
	.string "Dreams, adventure, and friendship\n"
	.string "awaits you, Kirby, and all the\l"
	.string "residents of Dream Land!\p"
	.string "We'll be seeing each other again\n"
	.string "to discuss things further soon.\p"
	.string "Take care now!\p"
	.string "$"
