gText_Birch_Welcome::
	.string "Hello! How do you do?\p"
	.string "They call me Wise Waddle Dee.\p"
	.string "And it is my great honor to welcome\n"
	.string "you to Dream Land!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "On your journey....”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "...you'll encounter hundreds of\n"
	.string "mysterious Helpers.\p"
	.string "Species from all across Planet\n"
	.string "Popstar, and even some from beyond,\l"
	.string "are gathering here in droves!\p"
	.string "They'll be invaluable companions\n"
	.string "to you during your travels.\p"
	.string "But just how many helpers are there?\n"
	.string "What makes them so cooperative?\l"
	.string "And just what has caused them to\l"
	.string "swarm throughout Dream Land...?\p"
	.string "That's what I've been researching.\p"
	.string "And during your journey, you may\n"
	.string "come across the answer as well...\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
