gText_ObtainedTheItem::
	.string "Obtained the {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "The BINDLE is full…$"

gText_PutItemInPocket::
	.string "Kirby put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} POCKET.$"

gText_PlayerFoundOneItem::
	.string "Kirby found one {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The BINDLE is full…$"

gText_PlayerPutItemInBag::
	.string "Kirby put away the {STR_VAR_2}\n"
	.string "in the BINDLE.$"

gText_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

gText_ObtainedTheItems::
	.string "Obtained {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "Kirby found {STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
	.string "Kirby put the COINS away in\n"
	.string "the COIN CASE.$"

gText_FoundXCoins::
	.string "Kirby found\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "Kirby found\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

gText_CoinCaseIsFull::
	.string "Too bad!\n"
	.string "The COIN CASE is full…$"

gText_NothingToPutThemIn::
	.string "Too bad!\n"
	.string "There's nothing to put them in…$"
