Text_BootUpPC:
	.string "Kirby booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed someone's PC.$"

gText_StorageSystemOpened::
	.string "Helper Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed Kirby's PC.$"

gText_AccessedLanettesPC::
	.string "Accessed Dedede's PC.$"

gText_AccessedBillsPC::
	.string "Accessed BILL's PC.$"
