Text_BootUpPC:
	.string "Kirby booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed SOMEONE'S PC.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed Kirby's PC.$"

gText_AccessedLanettesPC::
	.string "Accessed LANETTE's PC.$"

gText_AccessedBillsPC::
	.string "Accessed BILL's PC.$"
