# 1 "data/maps/KirbysHouse/scripts.pory"

# 2 "data/maps/KirbysHouse/scripts.pory"
KirbysHouse_MapScripts::
# 3 "data/maps/KirbysHouse/scripts.pory"
	.byte 0
# 4 "data/maps/KirbysHouse/scripts.pory"

# 5 "data/maps/KirbysHouse/scripts.pory"
KirbysHouse_EventScript_HouseSign::
# 6 "data/maps/KirbysHouse/scripts.pory"
	msgbox KirbysHouse_Text_KirbysHouse, MSGBOX_SIGN
# 7 "data/maps/KirbysHouse/scripts.pory"
	end
# 8 "data/maps/KirbysHouse/scripts.pory"

# 9 "data/maps/KirbysHouse/scripts.pory"
KirbysHouse_EventScript_Gooey::
# 10 "data/maps/KirbysHouse/scripts.pory"
	msgbox KirbysHouse_Text_Goo, MSGBOX_NPC
# 11 "data/maps/KirbysHouse/scripts.pory"
	end
# 12 "data/maps/KirbysHouse/scripts.pory"

# 13 "data/maps/KirbysHouse/scripts.pory"
KirbysHouse_EventScript_BandanaDee::
# 14 "data/maps/KirbysHouse/scripts.pory"
	msgbox KirbysHouse_Text_HelloKirby, MSGBOX_NPC
# 15 "data/maps/KirbysHouse/scripts.pory"
	end
# 16 "data/maps/KirbysHouse/scripts.pory"

# 17 "data/maps/KirbysHouse/scripts.pory"
KirbysHouse_Text_KirbysHouse:
# 18 "data/maps/KirbysHouse/scripts.pory"
	.string "KIRBY'S HOUSE\n"
# 19 "data/maps/KirbysHouse/scripts.pory"
	.string "Built by thankful Dream Land residents.$"
# 20 "data/maps/KirbysHouse/scripts.pory"

# 21 "data/maps/KirbysHouse/scripts.pory"
KirbysHouse_Text_Goo:
# 22 "data/maps/KirbysHouse/scripts.pory"
	.string "...goo?$"
# 23 "data/maps/KirbysHouse/scripts.pory"

# 24 "data/maps/KirbysHouse/scripts.pory"
KirbysHouse_Text_HelloKirby:
# 25 "data/maps/KirbysHouse/scripts.pory"
	.string "BANDANA WADDLE DEE: Hiya, Kirby!$"
